version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./backend:/app
      - ./backend/db:/app/db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  telegram-bot:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/db:/app/db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: python bot/main.py
    depends_on:
      - backend